services:
  terraform:
    build:
      context: .
      dockerfile: terraform.Dockerfile
    entrypoint: ["sh", "-c"]
    command: ["terraform init && terraform apply -auto-approve && terraform output function_url"]
  test:
    build:
      context: ./tests
      dockerfile: Dockerfile
    entrypoint: ["sh", "-c"]
    command: ["pytest test.py -v"]
    networks:
      - default
    profiles: ["test"]
